baseURL = "https://mobilitydb.github.io/libmeos-website/"
title = "MEOS"
theme = "hugo-geekdoc"
googleAnalytics = "G-FV2077JQZ8"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]
  # See https://geekdocs.de/usage/configuration/#site-configuration
  geekdocMenuBundle = true
  geekdocNextPrev = false
  geekdocRepo = "https://github.com/MobilityDB/MobilityDB"
